// Browser-only user tools. Watchlists never leave localStorage, and exports are
// assembled from data already shown in the current page.
const WATCH_KEY = 'sovereign-explorer-watchlist-v1';
export function watchlist() { try { const v = JSON.parse(localStorage.getItem(WATCH_KEY) || '[]'); return Array.isArray(v) ? v.filter((x) => typeof x === 'string').slice(0, 100) : []; } catch { return []; } }
export function isWatched(account) { return watchlist().includes(account); }
export function toggleWatch(account) { const v = watchlist(); const next = v.includes(account) ? v.filter((x) => x !== account) : [...v, account].slice(-100); localStorage.setItem(WATCH_KEY, JSON.stringify(next)); return next.includes(account); }
function cell(value) { const text = value == null ? '' : typeof value === 'object' ? JSON.stringify(value) : String(value); return /[",\n]/.test(text) ? `"${text.replaceAll('"', '""')}"` : text; }
export function downloadRows(filename, rows, format = 'json') { const values = Array.isArray(rows) ? rows : []; const keys = Object.keys(values[0] || {}); const body = format === 'csv' ? `${keys.map(cell).join(',')}\n${values.map((r) => keys.map((k) => cell(r[k])).join(',')).join('\n')}\n` : `${JSON.stringify(values, null, 2)}\n`; const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([body], { type: format === 'csv' ? 'text/csv' : 'application/json' })); link.download = filename; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 0); }
export function explainAction(action) { return ({ transfer: 'Moves transparent XUS from the signer to the recipient.', token_issue: 'Creates a transparent token supply and assigns it to an account.', token_transfer: 'Moves an issued token between transparent accounts.', token_burn: 'Permanently removes units of an issued token.', shielded: 'Applies a privacy-pool bundle without revealing note ownership or individual private flows.', htlc_lock: 'Locks XUS until its secret or refund condition is satisfied.', htlc_claim: 'Claims a hash-time-locked transfer by revealing its secret.', htlc_refund: 'Returns an expired hash-time-locked transfer.', call: 'Invokes a deployed contract with the displayed gas ceiling.', deploy: 'Publishes WebAssembly contract code on-chain.', register_name: 'Registers a Sovereign Name Service name.', transfer_name: 'Changes the account targeted by an SNS name.', nft_mint: 'Creates a non-fungible token.', nft_transfer: 'Transfers ownership of a non-fungible token.' })[action?.type] || 'A chain-native action. The exact indexed payload is preserved below.'; }
function hex(bytes) { return [...bytes].map((b) => b.toString(16).padStart(2, '0')).join(''); }
export async function verifyMerkleProof(proof, expectedRoot) { if (!proof) return { verified: false, reason: 'proof unavailable from relay' }; if (String(proof.algorithm || '').toLowerCase() !== 'sha256') return { verified: false, reason: `browser verifier does not support ${proof.algorithm || 'unspecified'} proofs` }; let current = String(proof.leaf || '').replace(/^0x/, '').toLowerCase(); for (const step of proof.path || []) { const sibling = String(step.hash || step.sibling || '').replace(/^0x/, '').toLowerCase(); const combined = step.side === 'left' ? sibling + current : current + sibling; const bytes = Uint8Array.from(combined.match(/../g) || [], (x) => parseInt(x, 16)); current = hex(new Uint8Array(await crypto.subtle.digest('SHA-256', bytes))); } const verified = current === String(expectedRoot || proof.root || '').replace(/^0x/, '').toLowerCase(); return { verified, reason: verified ? 'proof recomputed to the block header root' : 'proof does not match the block header root' }; }
